### PR TITLE
Build separate ANN benchmark

### PR DESCRIPTION
**Pull request by aressem**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by baldersheim — COMMENTED** [review]
I suspect the vespa-build-dependencies is not intentional.

**Comment by aressem** [comment]
I have not asked for a review yet :)

**Comment by baldersheim** [comment]
I'm eager to get this one on the way.... :)

**Comment by aressem** [comment]
PTAL @baldersheim . Screwdriver will fail to build this until 8.243.29 is released to opensource, but ok to merge.

**Review by baldersheim — APPROVED** [review]

**Pull request merged**
